apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: default
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9100'
spec:
  ports:
    - name: node-exporter
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  sessionAffinity: None
  type: ClusterIP
