apiVersion: v1
kind: Service
metadata:
  name: db-service-replica
spec:
  selector:
    app: postgres-db-slave
  ports:
    - name: postgres-slave #для удобного изменения порта в дальнейшем
      port: 5433 #порт в котором служба будет доступна
      targetPort: 5432 #порт контейнера куда служба будет перенаправлена
  type: ClusterIP