apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: postgres-db
  ports:
    - name: postgres-db #для удобного изменения порта в дальнейшем
      port: 5432 #порт в котором служба будет доступна
      targetPort: 5432 #порт контейнера куда служба будет перенаправлена
  type: ClusterIP