apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  selector:
    app: consul
  type: NodePort
  ports:
    - name: http
      port: 8500
      targetPort: 8500
      nodePort: 30085
    - name: dns
      port: 8600
      targetPort: 8600
      nodePort: 30086