apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  serviceName: consul
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8500
            - name: dns
              containerPort: 8600
          volumeMounts:
            - name: data
              mountPath: /consul/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi