apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - name: minio-console
      port: 9091
      targetPort: 9091
      nodePort: 30991
    - name: minio-mc
      port: 9000
      targetPort: 9000
      nodePort: 30900
  type: NodePort