apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio-service
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: minio
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9091
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key:  MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: MINIO_SECRET_KEY
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key:   MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio-password
          volumeMounts:
            - mountPath: /data
              name: volume
          ports:
            - name: minio-console
              containerPort: 9091
            - name: minio-mc
              containerPort: 9000
      volumes:
        - name: volume
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi