apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rmq
spec:
  serviceName: "rmq-service"
  replicas: 1
  selector:
    matchLabels:
      app: rmq
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
        - name: rmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: rmq-config
                  key: USER_NAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: rmq-config
                  key: USER_PASS
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: http
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: [ "rabbitmq-diagnostics", "status" ]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 15
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
            type: DirectoryOrCreate