apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rmq
spec:
  serviceName: "rmq-service"
  replicas: 1
  selector:
    matchLabels:
      app: rmq
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
        - name: rmq
          image: rabbitmq:3.11.16-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: rmq-config
                  key: USER_NAME
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: rmq-config
                  key: USER_PASS
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rabbitmq
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - rabbitmq-diagnostics -q check_running
            initialDelaySeconds: 60
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - rabbitmq-diagnostics -q check_running
                - rabbitmq-diagnostics -q check_local_alarms
            initialDelaySeconds: 60
            periodSeconds: 60
      volumes:
        - name: config-volume
          configMap:
            name: rabbitmq-config
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
              - key: enabled_plugins
                path: enabled_plugins