apiVersion: batch/v1
kind: Job
metadata:
  name: minio-client
spec:
  template:
    spec:
      containers:
        - name: minio-client
          image: minio
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: MINIO_SECRET_KEY
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: BUCKET_NAME
            - name: ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: minio-config
                  key: ENDPOINT
      restartPolicy: Never
  backoffLimit: 1