FROM bitnami/minideb:latest

RUN install_packages curl

ADD https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/linux/amd64/kubectl /usr/local/bin/kubectl

RUN chmod +x /usr/local/bin/kubectl