apiVersion: v1
kind: Service
metadata:
  name: backup-service
spec:
  selector:
    app: backup-server
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
