apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patroni-psql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patroni-psql
subjects:
  - kind: ServiceAccount
    name: patroni-psql