apiVersion: v1
kind: Service
metadata:
  name: patroni-psql-repl
  labels:
    application: patroni
    role: replica
spec:
  type: ClusterIP
  selector:
    application: patroni
    role: replica
  ports:
    - port: 5432
      targetPort: 5433