apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-slave
spec:
  selector:
    matchLabels:
      app: postgres-db-slave
  serviceName: db-service-slave
  replicas: 2
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: postgres-db-slave
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: db
          image: postgres:13.8
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - name: postgres-slave
              containerPort: 5432
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: init
          configMap:
            name: slave-config
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi